# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MetricasPaisagem
                                 A QGIS plugin
 Plugin que calcula diversas métricas de ecologia de paisagens 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-09-11
        copyright            : (C) 2023 by Francisco Santos 
        email                : mirandafrancisco977@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MetricasPaisagem class from file MetricasPaisagem.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .metricas_paisagem import MetricasPaisagem
    return MetricasPaisagem(iface)
